
# Add a Teacher
POST http://localhost:3000/teacher HTTP/1.1
Content-Type: application/json

{
    "name" : "bouhouch",
    "email": "bouhouch@gmail.com"
}


# Get a List of Teachers
GET http://localhost:3000/teacher HTTP/1.1
