# Teacher APIs

# Add a Teacher
POST http://localhost:3000/teachers HTTP/1.1
Content-Type: application/json

{
    "name": "Chamseddine Bouhouch",
    "email": "bouhouchchamseddine@gmail.com"
}

# Get a List of Teachers
GET http://localhost:3000/teachers HTTP/1.1

# Student APIs

# Add a Student
POST http://localhost:3000/students HTTP/1.1
Content-Type: application/json

{
    "name": "student1",
    "teacherId": 1
}

# Get a List of Students
GET http://localhost:3000/students HTTP/1.1

# Get Students by Teacher
GET http://localhost:3000/students/teacher/1 HTTP/1.1

# Update a Student
PATCH http://localhost:3000/students/1 HTTP/1.1
Content-Type: application/json

{
    "name": "updatedStudent1",
    "teacherId": 1
}

# Assignment APIs

# Assign an Assignment to Students
POST http://localhost:3000/assignments HTTP/1.1
Content-Type: application/json

{
    "title": "Nest ADN Homework",
    "dueDate": "2024-06-24",
    "studentIds": [1, 2],
    "teacherId":1
}

# Grade an Assignment
PATCH http://localhost:3000/assignments/1/grade HTTP/1.1
Content-Type: application/json

{
    "status": "Pass"
}

# Reporting APIs

# Basic Reporting for a Teacher
GET http://localhost:3000/assignments/report/teacher/1?date=2024-06-24 HTTP/1.1
